---
#  - name: apt-get update && apt-get upgrade (this takes a while)
#    apt:  update_cache=yes
#          upgrade=yes

  - name: Install python-software-properties,build-essential,python-virtualenv,python-pip,python-setuptools,heirloom-mailx,consolekit
    apt:  state=latest
          pkg=python-software-properties,build-essential,python-virtualenv,python-pip,python-setuptools,heirloom-mailx,consolekit

  - name: heirloom-mailx config
    template: src=etc.nail.rc.j2
          dest=/etc/nail.rc

  - name: add locale to /etc/environment
    lineinfile: dest=/etc/environment
          state=present
          regexp=^LC_ALL
          line='LC_ALL="en_US.UTF-8"'
